include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart" 
    - "**/generated_plugin_registrant.dart"

linter:
  rules:
    # Disable overly strict rules
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    one_member_abstracts: false
    use_late_for_private_fields_and_variables: false
